#!/usr/bin/env node
const {safeLoad} = require('js-yaml')
const optimist = require('optimist')

function readToEnd(stream, callback) {
  const chunks = []
  return stream
  .on('error', callback)
  .on('data', chunk => chunks.push(chunk))
  .on('end', () => callback(null, chunks))
}

const argparser = optimist
.usage([
  'Usage: yaml2json < data.yaml',
  '',
  'Convert YAML file to JSON',
].join('\n'))
.describe({help: 'print this help message'})
.boolean('help')

const argv = argparser.argv

if (argv.help) {
  argparser.showHelp()
}
else if (process.stdin.isTTY) {
  throw new Error('YAML must be piped in on STDIN')
}
else {
  readToEnd(process.stdin, function(err, chunks) {
    if (err) throw err
    const yaml = Buffer.concat(chunks)
    const obj = safeLoad(yaml)
    const json = JSON.stringify(obj)
    console.log(json)
  })
}
