#!/usr/bin/env node
const {safeLoad} = require('js-yaml')
const optimist = require('optimist')

function readToEnd(stream, callback) {
  const chunks = []
  return stream
  .on('error', callback)
  .on('data', chunk => chunks.push(chunk))
  .on('end', () => callback(null, chunks))
}

function convert(inputStream, outputStream, callback) {
  readToEnd(inputStream, (err, inputChunks) => {
    if (err) return callback(err)
    const inputString = Buffer.concat(inputChunks).toString()
    const object = safeLoad(inputString)
    const outputString = JSON.stringify(object)
    outputStream.write(outputString, callback)
  })
}

const argparser = optimist
.usage(`Usage: yaml2json < data.yaml

Convert YAML file to JSON`)
.describe({help: 'print this help message'})
.boolean('help')

const argv = argparser.argv

if (argv.help) {
  argparser.showHelp()
}
else if (process.stdin.isTTY) {
  throw new Error('YAML must be piped in on STDIN')
}
else {
  convert(process.stdin, process.stdout, err => {
    if (err) throw err
  })
}
